# Generated by Django 3.1.7 on 2021-04-08 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210408_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumbnail_small',
            new_name='thumbnail_alt',
        ),
    ]
