# Generated by Django 3.1.7 on 2021-04-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210408_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='quote',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='quote_author',
            field=models.TextField(blank=True),
        ),
    ]
