# Generated by Django 3.1.7 on 2021-04-15 11:56

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20210408_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='_content_alt_excerpt',
            field=models.TextField(default='temp', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='content_alt',
            field=model_utils.fields.SplitField(default='', no_excerpt_field=True),
        ),
    ]
