# Generated by Django 3.1.7 on 2021-04-15 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20210415_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='_content_alt_excerpt',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_alt',
        ),
    ]
